namespace: cisco
name: catalystwan
version: 0.3.3
readme: README.md
authors:
  - Arkadiusz Cichon <acichon@cisco.com>
  - Kamil Górski <kagorski@cisco.com>
description: Ansible collection to interact with Cisco SD-WAN Manager via catalystwan

repository: https://github.com/cisco-en-programmability/ansible-collection-catalystwan
documentation: https://github.com/cisco-en-programmability/ansible-collection-catalystwan/blob/main/README.md
homepage: https://github.com/cisco-en-programmability/ansible-collection-catalystwan
issues: https://github.com/cisco-en-programmability/ansible-collection-catalystwan/issues

license:
  - "GPL-3.0-only"

tags:
  - cisco
  - sdwan
  - catalystwan
  - networking

dependencies: {}
build_ignore: []
