# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

# --- Upload images directly to Manager --- #


- name: |
    Upload software image to Manager:
    - {{ vmanage_remote_software_filename }}
    - {{ viptela_remote_software_filename }}
    - {{ cedge_remote_software_filename }}
  cisco.catalystwan.software_repository:
    software:
      image_path: "{{ filename_item }}"
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  loop:
    - "{{ vmanage_remote_software_filename }}"
    - "{{ viptela_remote_software_filename }}"
    - "{{ cedge_remote_software_filename }}"
  loop_control:
    loop_var: filename_item

- name: "Filter list of all software images on Manager to find these manually uploaded"
  cisco.catalystwan.software_repository_info:
    category: "software_images"
    filters:
      version_type: "vmanage"
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  register: software_images_info

- name: "Assert that required images present on Manager Software Images list"
  ansible.builtin.assert:
    that:
      - software_images_info.software_images | length == 3
      - "{{ software_basenames | difference(all_available_files) | length == 0 }}"
    fail_msg: |
      Cannot find all required images, see:
      all_available_files: {{ all_available_files }}, software_files_names: {{ software_files_names }}
    success_msg: "All required files present on Manager Software Images list"
  vars:
    all_available_files: "{{ software_images_info.software_images | map(attribute='available_files') | list }}"
    software_basenames: "{{ software_files_names | map('basename') | list }}"
    software_files_names:
      - "{{ vmanage_remote_software_filename }}"
      - "{{ viptela_remote_software_filename }}"
      - "{{ cedge_remote_software_filename }}"
