# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Verify required variables for selected role
  ansible.builtin.include_tasks: variables_assertion.yml

- name: Set facts
  ansible.builtin.set_fact:
    url: "{{ (manager_instances | first).mgmt_public_ip }}"
    username: "{{ (manager_instances | first).admin_username }}"
    password: "{{ (manager_instances | first).admin_password }}"
    system_ip: "{{ (manager_instances | first).system_ip }}"

- name: Authenticate to Manager
  ansible.builtin.uri:
    url: "https://{{ url }}/j_security_check"
    method: POST
    body: "j_username={{ username }}&j_password={{ password }}"
    body_format: form-urlencoded
    validate_certs: false
    return_content: true
  register: login_response

- name: Check if login was successful
  ansible.builtin.fail:
    msg: "Manager Login failed. Check your credentials."
  when: '"JSESSIONID" not in login_response.cookies'

- name: Get Manager version
  ansible.builtin.uri:
    url: "https://{{ url }}/dataservice/device/system/info?deviceId={{ system_ip }}"
    method: GET
    validate_certs: false
    headers:
      Cookie: "JSESSIONID={{ login_response.cookies.JSESSIONID }}"
    return_content: true
    status_code: 200
  register: version_response
  when: '"JSESSIONID" in login_response.cookies'

- name: Set Manager version fact
  ansible.builtin.set_fact:
    manager_version: "{{ version_response.json.data[0].version }}"
  when: version_response is defined

- name: Ensure Manager version is greater than or equal to specified version
  ansible.builtin.fail:
    msg: "Manager software version {{ manager_version }} is lower than the required version {{ min_version_required }}."
  when: manager_version is version(min_version_required, '<')
