# .github/workflows/galaxy-importer.yml

# Its role is to performe the same checks that would be performed when publishing to galaxy
# Running them earlier helps to detect issues locally

name: galaxy-importer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  galaxy-importer:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible and importer
        run: |
          pip install ansible==9.4.0
          pip install ansible-importer
          pip install galaxy-importer

      - name: Build and install the collection
        run: |
          ansible-galaxy collection build $GITHUB_WORKSPACE --force
          ansible-galaxy collection install $GITHUB_WORKSPACE/*.tar.gz

      - name: Run ac-galaxy-importer
        run: |
          python -m galaxy_importer.main $GITHUB_WORKSPACE/*.tar.gz
