# .github/workflows/galaxy-importer.yml

name: Release to ansible-galaxy from tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-release:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get collection version from galaxy.yml
        id: collection-version
        run: |
          VERSION=$(grep '^version:' galaxy.yml | awk '{print $2}' | tr -d "'\"")
          echo "Collection version is $VERSION"
          echo "::set-output name=collection_version::$VERSION"

      - name: Get Git tag
        id: git-tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "Git tag is $TAG"
          echo "::set-output name=git_tag::$TAG"

      - name: Compare collection version and Git tag
        run: |
          COLLECTION_VERSION="${{ steps.collection-version.outputs.collection_version }}"
          GIT_TAG="${{ steps.git-tag.outputs.git_tag }}"
          if [[ "v$COLLECTION_VERSION" == "$GIT_TAG" ]]; then
            echo "The collection version matches the Git tag."
          else
            echo "Error: The collection version ($COLLECTION_VERSION) does not match the Git tag ($GIT_TAG)."
            exit 1
          fi

      # - name: Install Ansible and importer
      #   run: |
      #     pip install ansible==9.4.0

      # - name: Build and install the collection
      #   run: |
      #     ansible-galaxy collection build $GITHUB_WORKSPACE --force
      #     ansible-galaxy collection install $GITHUB_WORKSPACE/*.tar.gz

      # - name: Run ac-galaxy-importer
      #   run: |
      #     python -m galaxy_importer.main $GITHUB_WORKSPACE/*.tar.gz
